services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: micare_chat_postgres_jenkins
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/db_config/postgresql.conf

  micare_chat:
    image: fabio975/micare-chat
    restart: unless-stopped
    container_name: micare_chat_jenkins
    env_file:
      - ./.env
    environment:
      - SKIP_ENV_VALIDATION=true
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "${MICARE_CHAT_OUTSIDEPORT}:3000"
    depends_on:
      - postgres